#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to copy a VM image (SRC) to the image repository as DST
# Several SRC types are supported
###############################################################################

# -------- Set up the environment to source common tools & conf ------------ 

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
    TMCOMMON=/usr/lib/one/mads/tm_common.sh
else
    LIB_LOCATION=$ONE_LOCATION/lib
    TMCOMMON=$ONE_LOCATION/lib/mads/tm_common.sh
fi

. $LIB_LOCATION/sh/scripts_common.sh
source $(dirname $0)/fsrc

# include arg_path function
. $TMCOMMON

# include file with VG_NAME definition
source $ETC_LOCATION/tm_gfs2clvm/tm_gfs2clvmrc

SRC=$1
ID=$2
DST=`generate_image_path`
DST_BASENAME=$( basename "$DST" )
SRC_PATH=`arg_path $SRC`

# ------------ Copy the image to the repository ------------- 

case $SRC in
http://*)
    log "Downloading $SRC to the image repository"

    exec_and_log "$WGET -O $DST $SRC" \
        "Error downloading $SRC"

    exec_and_log "chmod 0660 $DST"
    ;;

vmware://*)
    SRC=`echo $SRC|sed  's/vmware:\/\///g'`

    if [ `check_restricted $SRC` -eq 1 ]; then
        log_error "Not allowed to copy images from $RESTRICTED_DIRS"
        error_message "Not allowed to copy image file $SRC"
        exit -1
    fi

    log "Copying local disk folder $SRC to the image repository"

    exec_and_log "cp -rf $SRC $DST" \
        "Error copying $SRC to $DST"

    if [ ! -f $DST/disk.vmdk ]; then
        BASE_DISK_FILE=`ls $DST | grep -v '.*-s[0-9]*\.vmdk'`

        exec_and_log "mv -f $DST/$BASE_DISK_FILE $DST/disk.vmdk" \
            "Error renaming disk file $BASE_DISK_FILE to disk.vmdk"
    fi

    exec_and_log "chmod 0770 $DST"
    ;;

lvm://*)
    #
    # copy of existing machine could be created
    # by using lvm://{{VMID}}/{{DISKID}}
    #
    vmid_diskid_pair=$( echo "$SRC" | sed 's,lvm://,,')
    vmid=$( echo "$vmid_diskid_pair" | cut -d "/" -f 1 )
    diskid=$( echo "$vmid_diskid_pair" | cut -d "/" -f 2 )
    src_volume_mapper_path=/dev/mapper/${VG_NAME}-lv--one--${vmid}--${diskid}
    src_volume=lv-one-${vmid}-${diskid}
    
    hostname=$(onehost list -l NAME,STAT | grep 'on$' | head -n 1 | awk '{print $1}')
    log "hostname: $hostname"
    #exec_and_log "ssh $hostname dd if=${src_volume_mapper_path} of=$DST" \
    #    "Error copying ${src_volume_mapper_path} to $DST"

    # $SSH $DST_HOST $SUDO $LVCREATE
    src_volume_size=$(set -x ; ssh $hostname sudo /sbin/lvs --noheadings --units m | grep $src_volume 2>/dev/null | ( read lv vg states size ; echo $size) )
    SIZE=${src_volume_size/M/}
    log "size: $SIZE"
    exec_and_log "ssh $hostname sudo lvcreate -L ${SIZE}M -n lv-oneimg-${DST_BASENAME} ${VG_NAME}" \
        "Error creating LV ${VG_NAME}/lv-oneimg-${DST_BASENAME}"
    exec_and_log "ssh $hostname dd if=/var/lib/one/${vmid}/images/disk.${diskid} of=/dev/mapper/${VG_NAME}-lv--oneimg--${DST_BASENAME}" \
        "Error copying /var/lib/one/${vmid}/images/disk.${diskid} to $DST_BASENAME"
    ;;

*)
    if [ `check_restricted $SRC` -eq 1 ]; then
        log_error "Not allowed to copy images from $RESTRICTED_DIRS"
        error_message "Not allowed to copy image file $SRC"
        exit -1
    fi
    
    log "Copying local image $SRC to the image repository"
    
    hostname=$(onehost list -l NAME,STAT | grep 'on$' | head -n 1 | awk '{print $1}')
    log "hostname: $hostname"
    src_volume_size=`fs_du $SRC $hostname`
    SIZE=${src_volume_size}
    log "size: $SIZE"
    exec_and_log "ssh $hostname sudo lvcreate -L ${SIZE}M -n lv-oneimg-${DST_BASENAME} ${VG_NAME}" \
        "Error creating LV ${VG_NAME}/lv-oneimg-${DST_BASENAME}"
    exec_and_log "ssh $hostname dd if=$SRC_PATH of=/dev/mapper/${VG_NAME}-lv--oneimg--${DST_BASENAME}" \
        "Error copying $SRC_PATH to $DST_BASENAME"
    ;;
esac

# ---------------- Get the size of the image & fix perms ------------


#SIZE=`fs_du $DST $hostname`
SIZE=$(ssh $hostname sudo /sbin/lvs --noheadings --units m | grep lv-oneimg-${DST_BASENAME} 2>/dev/null | ( read lv vg states size ; echo $size) )

echo "$DST $SIZE"
#echo "$DST 16384M"
