#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to move a VM image (SRC) to the image repository as DST
# Several SRC types are supported
###############################################################################

# ------------ Set up the environment to source common tools ------------ 

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh
source $(dirname $0)/fsrc

SRC=$1
DST=$2
ID=$3

# ------------ Generate a filename for the image ------------

if [ "$DST" = "-" ] ; then 
    DST=`generate_image_path`
fi
DST_BASENAME=$( basename "$DST" )

# ------------ Move the image to the repository ------------ 

case $SRC in
http://*)
    log "Downloading $SRC to the image repository"
    exec_and_log "$WGET -O $DST $SRC" \
        "Error downloading $SRC"
    ;;

*)
    log "Moving local image $SRC to the image repository"
 
    if [ \( -L $SRC \) -a \
         \( "`$READLINK -f $SRC`" = "`$READLINK -f $DST`" \) ] ; then
       log "Not moving files to image repo, they are the same"
    else

       log "No moving needed already existing volume should be on hashed lvm"
       exit 0


       log "mv SRC: $SRC"
       log "mv DST: $DST"
       # the whole db reseult for machine is present in the db even if it is already in shutdown/done state
       host_db_record=$( echo 'select * from vm_pool where oid = '"$ID"';' | sqlite3 /var/lib/one/one.db )
       log "host db recore: $host_db_record"
       # get the host IP where it was running before
       src_host=$(echo "$host_db_record" | sed -e 's,.*<HOSTNAME>,,')
       src_host=$(echo "$src_host" | sed -e 's,</HOSTNAME>.*,,')
       log "src hostname: $src_host"
       # check if the hostname is IP as it is used in our installation
       ( echo "$src_host" | grep -q "[^.]*\.[^.]*\.[^.]*\.[^.]*" ) || log "ERROR got bad hostname drom db"
       # using guessed node ip
       exec_and_log "ssh $src_host mv -f $SRC $DST" "Could not move $SRC to $DST"
    fi
    ;;
esac

if [ -d $DST ]; then
    exec_and_log "ssh $src_host chmod 0770 $DST"
else
    exec_and_log "ssh $src_host chmod 0660 $DST"
fi

# ---------------- Get the size of the image ------------
# if $src_host is defined, then this argument is used to call
# commands in fs_du via ssh
#SIZE=`fs_du $DST $src_host`
hostname=$src_host
SIZE=$(ssh $hostname sudo /sbin/lvs --noheadings --units m | grep lv-oneimg-${DST_BASENAME} 2>/dev/null | ( read lv vg states size ; echo $size) )
SIZE=${SIZE/.00m}

echo "$DST $SIZE"
