#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to remove a VM image (SRC) from the image repository 
###############################################################################

# ------------ Set up the environment to source common tools ------------ 

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh
source $(dirname $0)/fsrc

# include file with VG_NAME definition
source $ETC_LOCATION/tm_gfs2clvm/tm_gfs2clvmrc

# ------------ Remove the image to the repository ------------ 

SRC=$1
SRC_BASENAME=$( basename "$SRC" )

hostname=$(onehost list -l NAME,STAT | grep 'on$' | head -n 1 | awk '{print $1}')
log "hostname: $hostname"

exec_and_log "ssh $hostname sudo lvremove -f ${VG_NAME}/lv-oneimg-${SRC_BASENAME}" \
    "Error deleting ${VG_NAME}/lv-oneimg-${SRC_BASENAME}"

