#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2012, OpenNebula Project Leads (OpenNebula.org)             #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to create a VM image (SRC) of size (SIZE) and formatted
# as (FS)
###############################################################################

# ------------ Set up the environment to source common tools ------------

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh
source $(dirname $0)/fsrc

# include file with VG_NAME definition
source $ETC_LOCATION/tm_gfs2clvm/tm_gfs2clvmrc

# ------------ Create the image to the repository ------------

FSTYPE=$1
SIZE=$2
ID=$3

DST=`generate_image_path`
DST_BASENAME=$( basename "$DST" )

MKFS_CMD=`mkfs_command /dev/mapper/${VG_NAME}-lv--oneimg--${DST_BASENAME}" $FSTYPE`

hostname=$(onehost list -l NAME,STAT | grep 'on$' | head -n 1 | awk '{print $1}')
log "hostname: $hosname"

exec_and_log "ssh $hostname  sudo lvcreate -L 163840M -n lv-oneimg-${DST_BASENAME} ${VG_NAME}" \
    "Error creating LV ${VG_NAME}/lv-oneimg-${DST_BASENAME}"
exec_and_log "ssh $hostname $MKFS_CMD" \
    "Unable to create filesystem $FSTYPE in $DST"

# ---------------- Get the size of the image ------------
#SIZE=`fs_du $DST`

#echo "$DST $SIZE"
echo "$DST 163840"
